[project]
name = "waymo-mistakes-fri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-cognitiveservices-speech>=1.46.0",
    "fastmcp>=2.12.3",
]
